version: '3.8'
services:
  db_auth:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dss
      - POSTGRES_PASSWORD=dss
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    volumes: 
      - db_auth:/var/lib/postgresql/data
      - ./authMicroservice/database:/docker-entrypoint-initdb.d
  auth:
    build:
      context: ./authMicroservice
      dockerfile: Dockerfile
    
    ports:
      - '3001:3001'
    environment:
      -  DATABASE_URL=postgresql://dss:dss@db_auth/users
    volumes:
      -   ./shared/profile:/usr/src/app/src/static/profile:rw
    depends_on:
      - db_auth
      - apache
  apache:
    build:
      context: ./apache-server
      dockerfile: Dockerfile
      
    volumes:
      - ./shared:/usr/local/apache2/htdocs:ro
    ports:
      - "8080:80"
    
volumes:
  db_auth:
    driver: local
  shared_volume:
  

